---
title: "Algae_density"
format: html
editor_options: 
  chunk_output_type: console
---

Background

Hypotheses

H0 = invertebrate count does not change with increasing algae.
HA = invertebrate count does change with increasing algae.

```{r}
# load packages
library(tidyverse)
library(here)
library(stringr)
```

```{r}
# load data
toplayer_percent <- read_csv(here("data","KATMKEFJWPWS_2006-2024_randomPointContactCover_topLayerPercentCover.csv"))
total_percent <- read_csv(here("data", "KATMKEFJWPWS_2006-2024_randomPointContactCover_percentCover.csv"))
invert_count <- read_csv(here("data", "KATMKEFJWPWS_2006-2024_Nucella_Katharina_Lirabuccinum_Count.csv"))
```

```{r}
# add region column to all data
total_percent <- total_percent %>% 
  mutate(region = str_sub(SiteID, 1, 3))
toplayer_percent <- toplayer_percent %>% 
  mutate(region = str_sub(SiteID, 1, 3))
invert_count <- invert_count %>% 
  mutate(region = str_sub(SiteID, 1, 3))
```

```{r}
sum_invert_count <- invert_count %>% 
  group_by(SampleDate, region, Elevation_Position) %>% 
  summarise(invert_count = sum(Density_individual2SqM))
sum_percent <- total_percent %>% 
  group_by(SampleDate, region, Elevation_Position, Quadrat_Num) %>% 
  summarise(sum = sum(Percent_Cover)) %>% 
  summarise(total_percent = mean(sum))

invert_algae_join <- left_join(sum_invert_count, sum_percent, by = c("SampleDate", "region", "Elevation_Position"))

ggplot(invert_algae_join, aes(x = total_percent, y = invert_count))+
  geom_point()

ggplot(invert_algae_join, aes(x = invert_count)) +
  geom_bar()
```

DAG

Data and Model Simulation
y ~ negbinom (mu, theta)
log(mu) = beta0 + beta1 * predictor

mu = r(1-p) / p

```{r}
set.seed(42)
# set coefficients and parameters
# mu <- 1
# theta <- 3
beta0 <- -2
beta1 <- 0.7
theta <- 0.6
# probability <- 0.5

x <- rnorm(1000, mean = 10, sd = 0.5)

log_mu <- beta0 + beta1 * x
mu <- exp(log_mu)

y <- rnbinom(1000, mu = mu, size = theta)

simulate_mod <- glm.nb(y ~ x,
                       data = tibble(x, y))
summary(simulate_mod)
```


Negative Binomial Model

```{r}
glm.nb(invert_count ~ total_percent + SampleDate + region + Elevation_Position, data = invert_algae_join, link = log)
```


Conclusion